import React from "react"
import { Button } from 'primereact/button'
import { InputText } from 'primereact/inputtext'
import { Toast } from 'primereact/toast'
import { useRouter } from 'next/router'
import { configData } from "../../../config"
import Head from "next/head"
const url_backend = configData.API_BACKEND;

export default function Register() {

    const toastify = React.useRef<Toast>(null)
    const router = useRouter();
    const [disable, setDisable] = React.useState<boolean>(false);

    const handleSubmit = async (ev: React.FormEvent<HTMLFormElement>) => {
        ev.preventDefault();
        setDisable(true);
        const formData = new FormData(ev.target as HTMLFormElement);
        const body = Object.fromEntries(formData.entries())

        const registerFetch = await fetch(`${url_backend}/register`, {
            method: 'POST',
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(body)
        });

        if (registerFetch.ok) {
            const responseSuccess = await registerFetch.json();
            setDisable(false)
            toastify.current?.show({
                severity: 'success',
                summary: "Register Account",
                detail: responseSuccess?.message
            });
            return router.push('/auth/login')
        }

        if (!registerFetch.ok) {
            setDisable(false)
            const bodyError = await registerFetch.json();
            toastify.current?.show({
                severity: 'error',
                summary: "Error",
                detail: bodyError?.message
            })
        }
    }

    return (
        <React.Fragment>
            <Toast ref={toastify} />
            <Head>
                <title>Register Pakan Ikan</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <form onSubmit={handleSubmit}>
                <div className="grid p-fluid" style={{ fontSize: '14px' }}>
                    <div className="col-12">
                        <div className="flex flex-column gap-2">
                            <label htmlFor="username">Nama Lengkap</label>
                            <InputText
                                type="text"
                                className="p-inputtext-sm"
                                placeholder="Nama Lengkap"
                                id="full_name"
                                name="full_name"
                                aria-describedby="username-help" />
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="flex flex-column gap-2">
                            <label htmlFor="username">Email</label>
                            <span className="p-input-icon-right">
                                <i className="pi pi-eye" />
                                <InputText
                                    className="p-inputtext-sm"
                                    type="email"
                                    name="username"
                                    placeholder="Masukan Email Anda" />
                            </span>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="flex flex-column gap-2">
                            <label htmlFor="username">Password</label>
                            <InputText
                                type="password"
                                className="p-inputtext-sm"
                                placeholder="Masukan Kata Sandi"
                                id="password"
                                name="password"
                                aria-describedby="username-help" />
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="flex flex-column gap-2">
                            <label htmlFor="username">Confirm Password</label>
                            <InputText
                                type="password"
                                className="p-inputtext-sm"
                                placeholder="Konfirmasi Kata Sandi"
                                id="confirm_password"
                                name="confirm_password"
                                aria-describedby="username-help" />
                        </div>
                    </div>
                    <div className="col-12">
                        <Button
                            rounded
                            disabled={disable}
                            type="submit"
                            label="Register"
                            size="small" />
                    </div>
                </div>
            </form>
        </React.Fragment>
    )
}

Register.getLayoutAuth = function (page: React.ReactElement) {
    return page;
}