import Head from 'next/head'
import { Inter } from 'next/font/google'
import React from 'react'
import { LoadingComponent } from '../../layout/layoutContextDasboard'
import { useRouter } from 'next/router'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();

  React.useEffect(() => {
    setTimeout(() => {
      router.push('/auth/login')
    }, 2000)
  }, [])

  return (
    <>
      <Head>
        <title>Web App Pakan Ikan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoadingComponent/>
    </>
  )
}

Home.getLayoutIndex=  function (page: React.ReactElement) {
  return page;
}
